### ISSUE TITLE
Inconsistent failures when running test suite in parallel

### ISSUE THREAD

**Issue by ryandens** [pact-foundation/pact-jvm#1223]
## Background 
I recently added some tests using the `au.com.dius.pact.consumer:junit5` artifact to a test suite which leverages [JUnit 5's experimental parallel test execution](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution) feature. I'm seeing some inconsistent failures with my pact tests classes (that have multiple methods annotated with pact in them) with the following error:
```
 java.lang.AssertionError: The following methods annotated with @Pact were not executed during the test: TestClass.pactMethod
    If these are currently a work in progress, and a @Disabled annotation to the method
        at au.com.dius.pact.consumer.junit5.PactConsumerTestExt.afterAll(PactConsumerTestExt.kt:340)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$13(ClassBasedTestDescriptor.java:425)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$14(ClassBasedTestDescriptor.java:425)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllCallbacks(ClassBasedTestDescriptor.java:425)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:213)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:78)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:145)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:145)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

I don't expect pact-jvm to have first class support for an experimental junit 5 feature, but I took a look at the relevant code in `PactConsumerTestExt` and I think I've narrowed down the issue and am curious if you'd be open to a fix

## Description of the issue in the code
The `PactConsumerTestExt` instantiates a `MutableList<Method>` before all tests are executed for a given test class. This list is then put in junit's extension `ExtensionContext.Store`. This currently happens on [PactConsumerTestExt.kt#L221](https://github.com/DiUS/pact-jvm/blob/master/consumer/junit5/src/main/kotlin/au/com/dius/pact/consumer/junit5/PactConsumerTestExt.kt#L221)

 Next, before the test is executed, the pact method is added to that list. This currently happens on [PactConsumerTestExt.kt#L345](https://github.com/DiUS/pact-jvm/blob/master/consumer/junit5/src/main/kotlin/au/com/dius/pact/consumer/junit5/PactConsumerTestExt.kt#L345)

Finally, the code responsible for throwing the above exception is executed after all tests are completed. The list is retrieved from the `Store` and the size of the list is compared against the number of expected methods. This currently happens on [PactConsumerTestExt.kt#L414](https://github.com/DiUS/pact-jvm/blob/master/consumer/junit5/src/main/kotlin/au/com/dius/pact/consumer/junit5/PactConsumerTestExt.kt#L414).

This functions perfectly with normal test execution, and most of the time with parallel test execution but I think it is the root cause of the race condition I described above. 

## The fix
I think the appropriate way to fix this would be to synchronize access to this object. That way, when `PactConsumerTestExt#afterAll` runs, it will be blocked on reading the size of the collection if  `PactConsumerTestExt#lookupPact` is currently writing to the collection. 

With that in mind, I think the fix is pretty straightforward. I would replace the following line of code [PactConsumerTestExt.kt#L221](https://github.com/DiUS/pact-jvm/blob/master/consumer/junit5/src/main/kotlin/au/com/dius/pact/consumer/junit5/PactConsumerTestExt.kt#L221) to instead be:
```kotlin
store.put("executedFragments", ConcurrentHashMap.newKeySet<Method>())
```

Then, I would replace subsequent access to this object with type `MutableSet<Method>` rather than `MutableList<Method>` since nothing in the extension relies on any ordering of the `executedFragments` list.

**Comment by ryandens** [comment]
@uglyog any thoughts on this? I'd be happy to send a PR your way

**Comment by uglyog** [comment]
a PR is always welcome. You fix makes sense to me.
