### ISSUE TITLE
Pact match path not working with regex 

### ISSUE THREAD

**Issue by sumanguduru** [pact-foundation/pact-jvm#1296]
" .matchPath("/v1/agents/[0-9]+/profile/^(\\w{1,25})(\\.\\w{0,25})?(@abc)$/get")
i'm getting below error when i add the regex to match path "^(\\w{1,25})(\\.\\w{0,25})?(@abc)$"  , 
my path looks like /v1/agents/123/profile/shop.snc@abc/get

java.lang.StackOverflowError
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at dk.brics.automaton.State.getSortedTransitionArray(Unknown Source)
	at dk.brics.automaton.State.getSortedTransitions(Unknown Source)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:340)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:366)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:366)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:366)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:366)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:366)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:366)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:366)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:366)

**Comment by joklek** [comment]
This looks like a bug with the Generex library, which was last updated in 2016, so I'd not put much hope into a fix for this.

A workaround would be to think whether you actually need such a complex regex for matching. I'm still reading up on Pact, but the docs mention Postels law, which says that:

> As a rule of thumb, you generally want to use exact matching when you're setting up the expectations for a request (upon_receiving(...).with(...)) because you're under control of the data at this stage, and according to Postel's Law, we want to be "strict" with what we send out

[source](https://docs.pact.io/getting_started/matching/#request-matching)

My interpretation of it is that you don't need regexes in your request path in the parts where you can control the URL

**Comment by uglyog** [comment]
Agree with what @joklek said. I once saw a quote something like: You have a problem, so you use a regex to solve it. Now you have two problems.

In addition, you haven't given an example value, so it is trying to generate the example value off the regex. That regex is too complex to do that. You need to provide an actual example as the second parameter.
