### ISSUE TITLE
400 Bad Request when switching provider tests to pactflow.io service

### ISSUE THREAD

**Issue by juan-fernandez-enverus** [pact-foundation/pact-jvm#1313]
Hello

I have some tests for a spring boot application working against a local pact broker. But when I switch to a pactflow.io service it fails:

Application is using last version in mvnrepository

```
  <groupId>au.com.dius</groupId>
  <artifactId>pact-jvm-provider-spring</artifactId>
  <version>4.0.10</version>
```

Configuration from
```
pactbroker:
  host: "localhost"
  port: "9292"
  protocol: "http"
```

Configuration to
```
pactbroker:
  host: "enverus.pactflow.io"
  port: "443"
  protocol: "https"
  auth:
    token: "***"
    scheme: "Bearer"
```

Result

```
au.com.dius.pact.core.pactbroker.RequestFailedException: Request to path '/' failed with response 'HTTP/1.1 400 Bad Request'
	at au.com.dius.pact.core.pactbroker.HalClient.handleHalResponse(HalClient.kt:327)
	at au.com.dius.pact.core.pactbroker.HalClient.getJson(HalClient.kt:312)
	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:273)
	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:268)
	at au.com.dius.pact.core.pactbroker.HalClient.navigate(HalClient.kt:261)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.fetchConsumers(PactBrokerClient.kt:94)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.kt:140)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.load(PactBrokerLoader.kt:92)
	at au.com.dius.pact.provider.junit.PactRunner.initialize(PactRunner.kt:85)
	at au.com.dius.pact.provider.junit.PactRunner.getChildren(PactRunner.kt:140)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:78)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

So far I cannot see the issue... Could you help me understand this error, please?

**Comment by uglyog** [comment]
What version of Pact-JVM are you using?

**Comment by uglyog** [comment]
Ah! 4.0.10, can you try 4.1.17?

```
<dependency>
  <groupId>au.com.dius.pact.provider</groupId>
  <artifactId>spring</artifactId>
  <version>4.1.17</version>
</dependency>
```

**Comment by juan-fernandez-enverus** [comment]
Hello @uglyog,

Thank you very much for your answer... I did not realized that artifacts got reorganized. Sadly, it is still failing using 4.1.17 or 4.2.0 but the error is a little bit more verbose.

All dependencies are properly updated as far as I can check:

![image](https://user-images.githubusercontent.com/79534682/108989304-bb544980-7695-11eb-9720-08c99e5d3353.png)

Current error:

```
au.com.dius.pact.core.pactbroker.RequestFailedException: Request to path '/' failed with response 'HTTP/1.1 400 Bad Request'
	at au.com.dius.pact.core.pactbroker.HalClient.handleHalResponse(HalClient.kt:301)
	at au.com.dius.pact.core.pactbroker.HalClient.access$handleHalResponse(HalClient.kt:140)
	at au.com.dius.pact.core.pactbroker.HalClient$getJson$1.invoke(HalClient.kt:284)
	at au.com.dius.pact.core.pactbroker.HalClient$getJson$1.invoke(HalClient.kt:140)
	at au.com.dius.pact.core.support.KotlinLanguageSupportKt.handleWith(KotlinLanguageSupport.kt:38)
	at au.com.dius.pact.core.pactbroker.HalClient.getJson(HalClient.kt:278)
	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:242)
	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:237)
	at au.com.dius.pact.core.pactbroker.HalClient.navigate(HalClient.kt:219)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient$fetchConsumersWithSelectors$halClient$navigateResult$1.invoke(PactBrokerClient.kt:204)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient$fetchConsumersWithSelectors$halClient$navigateResult$1.invoke(PactBrokerClient.kt:138)
	at au.com.dius.pact.core.support.KotlinLanguageSupportKt.handleWith(KotlinLanguageSupport.kt:38)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.fetchConsumersWithSelectors(PactBrokerClient.kt:204)
	at au.com.dius.pact.provider.junitsupport.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.kt:209)
	at au.com.dius.pact.provider.junitsupport.loader.PactBrokerLoader.load(PactBrokerLoader.kt:111)
	at au.com.dius.pact.provider.junit.PactRunner.initialize(PactRunner.kt:96)
	at au.com.dius.pact.provider.junit.PactRunner.getChildren(PactRunner.kt:151)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:78)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
au.com.dius.pact.core.pactbroker.InvalidNavigationRequest: Failed to fetch the root HAL document
	at au.com.dius.pact.core.pactbroker.HalClient.navigate(HalClient.kt:223)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient$fetchConsumersWithSelectors$halClient$navigateResult$1.invoke(PactBrokerClient.kt:204)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient$fetchConsumersWithSelectors$halClient$navigateResult$1.invoke(PactBrokerClient.kt:138)
	at au.com.dius.pact.core.support.KotlinLanguageSupportKt.handleWith(KotlinLanguageSupport.kt:38)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.fetchConsumersWithSelectors(PactBrokerClient.kt:204)
	at au.com.dius.pact.provider.junitsupport.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.kt:209)
	at au.com.dius.pact.provider.junitsupport.loader.PactBrokerLoader.load(PactBrokerLoader.kt:111)
	at au.com.dius.pact.provider.junit.PactRunner.initialize(PactRunner.kt:96)
	at au.com.dius.pact.provider.junit.PactRunner.getChildren(PactRunner.kt:151)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:78)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: au.com.dius.pact.core.pactbroker.RequestFailedException: Request to path '/' failed with response 'HTTP/1.1 400 Bad Request'
	at au.com.dius.pact.core.pactbroker.HalClient.handleHalResponse(HalClient.kt:301)
	at au.com.dius.pact.core.pactbroker.HalClient.access$handleHalResponse(HalClient.kt:140)
	at au.com.dius.pact.core.pactbroker.HalClient$getJson$1.invoke(HalClient.kt:284)
	at au.com.dius.pact.core.pactbroker.HalClient$getJson$1.invoke(HalClient.kt:140)
	at au.com.dius.pact.core.support.KotlinLanguageSupportKt.handleWith(KotlinLanguageSupport.kt:38)
	at au.com.dius.pact.core.pactbroker.HalClient.getJson(HalClient.kt:278)
	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:242)
	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:237)
	at au.com.dius.pact.core.pactbroker.HalClient.navigate(HalClient.kt:219)
	... 15 more
```

**Comment by juan-fernandez-enverus** [comment]
My bad... Debugging the code I have realized that I was using the wrong properties. It was trying to access using http instead of https

![image](https://user-images.githubusercontent.com/79534682/108992255-61ee1980-7699-11eb-81a1-b9d1e2df6a27.png)
