### ISSUE TITLE
Error verifying contract on provider test

### ISSUE THREAD

**Issue by naushadamin** [pact-foundation/pact-jvm#1377]
Hello,

I am getting the following error while trying to run a Junit4 unit test on a SpringBoot project:

0 - No signature of method: au.com.dius.pact.model.Request.generatedRequest() is applicable for argument types: () values: []

	at au.com.dius.pact.provider.junit.target.BaseTarget.getAssertionError(BaseTarget.java:80)
	at au.com.dius.pact.provider.junit.target.HttpTarget.testInteraction(HttpTarget.java:124)
	at au.com.dius.pact.provider.junit.InteractionRunner$2.evaluate(InteractionRunner.java:236)
	at au.com.dius.pact.provider.junit.RunStateChanges.evaluate(RunStateChanges.java:26)
	at au.com.dius.pact.provider.spring.SpringBeforeRunner.evaluate(SpringInteractionRunner.kt:31)

gradle plugin version : 4.1.7
pact-jvm-provider-junit_2.12:3.5.24
pact-jvm-provider-spring_2.11:3.5.24

**Comment by mefellows** [comment]
Is there a reason the library versions between spring and junit aren't the same? Could that be the issue?

**Comment by naushadamin** [comment]
Same issue with pact-jvm-provider-junit_2.11:3.5.24 version

**Comment by naushadamin** [comment]
I found the issue. Having au.com.dius:pact-jvm-model:3.5.3 this dependency as testCompile was causing the issue
