### ISSUE TITLE
Pact verification is failing while validating provider endpoint with pfx certification

### ISSUE THREAD

**Issue by PRABAREPO** [pact-foundation/pact-jvm#1394]
Pact verification is failing while validating provider endpoint with pfx certification

**Below section is part of Pact verification section in my POM.xml :**

<plugin>
				<groupId>au.com.dius</groupId>
				<artifactId>pact-jvm-provider-maven</artifactId>
				<version>4.0.10</version>
				<configuration>
					<serviceProviders>
						<serviceProvider>
							<name>Test_Provider</name>
							<insecure>false</insecure>
							<trustStore>./src/cert/testcertificate.pfx</trustStore>
							<trustStorePassword>****************</trustStorePassword>
							<protocol>https</protocol>
							<host>lambda*******.org</host>
							<port>443</port>
							<path>/</path>
							<pactBroker>
								<url>https://pact.broker*****.com/</url>
								<authentication>
									<username>Test_User</username>
									<password>********</password>
								</authentication>
							</pactBroker>
						</serviceProvider>
					</serviceProviders>
					<configuration>
						<pact.showStacktrace>true</pact.showStacktrace>
					</configuration>
				</configuration>
			</plugin>

When I do pact verification using "**mvn pact:verify**" command in command prompt, I am getting below error message.

**Request Failed - PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:642)**

Could anyone help on this ?

**Comment by uglyog** [comment]
Can you provide the version of the JVM you are using?

**Comment by uglyog** [comment]
The `trustStore` must be a Java trust store (JKS format), you can't use a certificate. You can create a JKS keystore and import the PFX file into it. See https://blogs.oracle.com/blogbypuneeth/steps-to-create-a-jks-keystore-from-pfx-file
