### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce

### ISSUE THREAD

**Issue by charlenew** [pact-foundation/pact-jvm#1445]
using below dependency but got error 
       <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-provider-spring_2.12</artifactId>
            <version>3.6.7</version>
        </dependency>
17:28:15.451 [main] DEBUG au.com.dius.pact.provider.spring.MvcProviderVerifier - Response: {statusCode=400, headers={Content-Type=[application/json]}, contentType=application/json, data={"responseCode":"400"}}

java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce

	at au.com.dius.pact.provider.ResponseComparison$Companion.compareResponse(ResponseComparison.kt:131)
	at au.com.dius.pact.provider.ProviderVerifierBase.verifyRequestResponsePact(ProviderVerifier.kt:381)
	at au.com.dius.pact.provider.spring.MvcProviderVerifier.verifyResponseFromProvider(MvcProviderVerifier.kt:49)
	at au.com.dius.pact.provider.spring.target.MockMvcTarget.testInteraction(MockMvcTarget.kt:73)
	at au.com.dius.pact.provider.junit.InteractionRunner$interactionBlock$statement$1.evaluate(InteractionRunner.kt:197)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.kt:144)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:137)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:51)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 21 more

**Comment by uglyog** [comment]
That version id no longer supported. Please use 

For JDK 8:
```
<dependency>
  <groupId>au.com.dius.pact.provider</groupId>
  <artifactId>spring</artifactId>
  <version>4.1.27</version>
</dependency>
```

For JDK 11+
```
<dependency>
  <groupId>au.com.dius.pact.provider</groupId>
  <artifactId>spring</artifactId>
  <version>4.2.12</version>
</dependency>
```
