### ISSUE TITLE
confusing condition about usage the combination of `numberType` and `MockServer` 

### ISSUE THREAD

**Issue by firatpayalan** [pact-foundation/pact-jvm#1498]
there is a confusing condition about usage the combination of `numberType` and `MockServer` while perfoming consumer test. sample that below would not be accepted from MockServer. 

```
    DslPart transSearchResp = LambdaDsl.newJsonBody((response) -> response
            .numberType("page")
    ).build();

    @Pact(consumer = "wallet-campaign",provider = "wallet-query")
    public RequestResponsePact getTransactions(PactDslWithProvider builder) {

        return builder
                .given("it_should_get_transactions")
                .uponReceiving("a request for wallet transaction")
                .headers(requestHeaders)
                .method("GET")
                .path("/v1/internal/wallets/1/transactions/search")
                .willRespondWith()
                .status(HttpStatus.OK.value())
                .body(transSearchResp)
                .toPact();
    }

```
While using this sample, the server throws  `org.apache.http.NoHttpResponseException: 127.0.0.1:9092 failed to respond` as an exception. 

```
16:47:06.427 [Test worker] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to /127.0.0.1:9092
16:47:06.428 [Test worker] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connection established 127.0.0.1:63331<->127.0.0.1:9092
16:47:06.429 [Test worker] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request GET /v1/internal/wallets/1/transactions/search HTTP/1.1
16:47:06.430 [Test worker] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
16:47:06.430 [Test worker] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
16:47:06.431 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> GET /v1/internal/wallets/1/transactions/search HTTP/1.1
16:47:06.431 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> content-type: application/json
16:47:06.432 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> x-correlationid: contract-test
16:47:06.432 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> x-storefrontid: 1
16:47:06.432 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> x-applicationid: 1
16:47:06.432 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> x-channelid: 1
16:47:06.432 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> Host: 127.0.0.1:9092
16:47:06.432 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> Connection: Keep-Alive
16:47:06.432 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> User-Agent: Apache-HttpClient/4.5.10 (Java/11.0.6)
16:47:06.433 [Test worker] DEBUG org.apache.http.headers - http-outgoing-3 >> Accept-Encoding: gzip,deflate
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "GET /v1/internal/wallets/1/transactions/search HTTP/1.1[\r][\n]"
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "content-type: application/json[\r][\n]"
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "x-correlationid: contract-test[\r][\n]"
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "x-storefrontid: 1[\r][\n]"
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "x-applicationid: 1[\r][\n]"
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "x-channelid: 1[\r][\n]"
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "Host: 127.0.0.1:9092[\r][\n]"
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "Connection: Keep-Alive[\r][\n]"
16:47:06.433 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "User-Agent: Apache-HttpClient/4.5.10 (Java/11.0.6)[\r][\n]"
16:47:06.434 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "Accept-Encoding: gzip,deflate[\r][\n]"
16:47:06.434 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 >> "[\r][\n]"
16:47:06.434 [HTTP-Dispatcher] DEBUG au.com.dius.pact.consumer.BaseJdkMockServer - Received request: 	method: GET
	path: /v1/internal/wallets/1/transactions/search
	query: {}
	headers: {Accept-encoding=[gzip,deflate], Connection=[Keep-Alive], Host=[127.0.0.1:9092], User-agent=[Apache-HttpClient/4.5.10 (Java/11.0.6)], X-channelid=[1], Content-type=[application/json], X-applicationid=[1], X-storefrontid=[1], X-correlationid=[contract-test]}
	matchers: MatchingRules(rules={})
	generators: Generators(categories={})
	body: EMPTY
16:47:06.435 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.RequestMatching - comparing to expected request: 
	method: GET
	path: /v1/internal/wallets/1/transactions/search
	query: {}
	headers: {x-storefrontid=[1], x-channelid=[1], x-correlationid=[contract-test], x-applicationid=[1], content-type=[application/json]}
	matchers: MatchingRules(rules={path=Category(name=path, matchingRules={}), header=Category(name=header, matchingRules={})})
	generators: Generators(categories={})
	body: MISSING
16:47:06.436 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.HeaderMatcher - Comparing header 'content-type': 'application/json' to 'application/json'
16:47:06.436 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.HeaderMatcher - Comparing content type header: 'application/json' to 'application/json'
16:47:06.436 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.HeaderMatcher - Comparing header 'x-applicationid': '1' to '1'
16:47:06.437 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.HeaderMatcher - Comparing header 'x-channelid': '1' to '1'
16:47:06.437 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.HeaderMatcher - Comparing header 'x-correlationid': 'contract-test' to 'contract-test'
16:47:06.437 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.HeaderMatcher - Comparing header 'x-storefrontid': '1' to '1'
16:47:06.437 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.Matching - Found a matcher for application/json -> au.com.dius.pact.core.matchers.JsonBodyMatcher@568c36be
16:47:06.438 [HTTP-Dispatcher] DEBUG au.com.dius.pact.core.matchers.RequestMatching - Request mismatch: []
16:47:06.438 [Test worker] DEBUG org.apache.http.wire - http-outgoing-3 << "end of stream"
16:47:06.438 [Test worker] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-3: Close connection
16:47:06.439 [Test worker] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-3: Shutdown connection
16:47:06.439 [Test worker] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
16:47:06.439 [Test worker] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 2][route: {}->http://127.0.0.1:9092][total kept alive: 0; route allocated: 0 of 100; total allocated: 0 of 200]
16:47:06.439 [Test worker] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:9092: The target server failed to respond
16:47:06.439 [Test worker] DEBUG org.apache.http.impl.execchain.RetryExec - The target server failed to respond
org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
	at org.apache.http.client.fluent.Request.execute(Request.java:177)

```
 
However the value parameter is added, the server will accept the response as body and everything works smoothly. 

```
    DslPart transSearchResp = LambdaDsl.newJsonBody((response) -> response
            .numberType("page",1)
    ).build();
```

could i be missed anything ?  

library info
```
au.com.dius:pact-jvm-consumer-junit5:4.0.2
au.com.dius:pact-jvm-provider-junit5:4.0.2
au.com.dius:pact-jvm-provider-spring:4.0.10
au.com.dius:pact-jvm-consumer-java8:4.0.9
```

**Comment by firatpayalan** [comment]
just found the problem, 

it was a misunderstanding the library usage 🙈  
`pact-` prefixed dependencies are getting deprecated. when those four dependencies;

```
au.com.dius:pact-jvm-consumer-junit5:4.0.2
au.com.dius:pact-jvm-provider-junit5:4.0.2
au.com.dius:pact-jvm-provider-spring:4.0.10
au.com.dius:pact-jvm-consumer-java8:4.0.9
```

are replaced the only `au.com.dius.pact.consumer:junit5:4.3.2` version. it has worked successfully 🥳🥳🥳
