### ISSUE TITLE
Unexpected character 'EOI(null)' at position '3', expecting '[DOT]'

### ISSUE THREAD

**Issue by achawla-Branch** [pact-foundation/pact-jvm#1563]
Not sure if it's a bug.

Parsing against V4 version is failing as below because it's expecting minor version as well. 

 ```fun versionString(): String {
    return when (this) {
      V1 -> "1.0.0"
      V1_1 -> "1.1.0"
      V2 -> "2.0.0"
      V3 -> "3.0.0"
      V4 -> "4.0" <---
      else -> "3.0.0"
    }
  }

Unexpected character 'EOI(null)' at position '3', expecting '[DOT]'
	at app//com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
	at app//com.github.zafarkhaja.semver.VersionParser.parseVersionCore(VersionParser.java:288)
	at app//com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:255)
	at app//com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
	at app//com.github.zafarkhaja.semver.Version.valueOf(Version.java:265)
	at app//au.com.dius.pact.core.model.DefaultPactReader.loadPact(PactReader.kt:180)```

**Comment by rholshausen** [comment]
What version are you using? This has been fixed in 4.2.x+

**Comment by BorealFeast** [comment]
I confirm this is happening on 4.3.9 and 4.3.14
see the snippet from the generated pact :
```
"metadata": {
    "pact-jvm": {
      "version": "4.3.14"
    },
    "pactSpecification": {
      "version": "4.0"
    }
  }
```

**Comment by ocridlig** [comment]
I have the same problem with the versions 4.5.5 and 4.5.6.

![pact](https://user-images.githubusercontent.com/25746084/233442111-c393f247-a2cd-452e-8316-92a20c0e5f8e.png)

When do you think this problem will be solved?
Is there a workaround to avoid the error?

Thanks

**Comment by rholshausen** [comment]
The `Unexpected character 'EOI(null)' at position '3', expecting '[DOT]'` exception was fixed in 4.2.x, and com.github.zafarkhaja.semver.VersionParser is no longer used since then.

**Comment by sachinsonu** [comment]
Can this issue be also fixed in 4.1.x release ?

**Comment by rholshausen** [comment]
4.1.42 has been released with the fix
