### ISSUE TITLE
On upgrade PactBrokerClient: URI path begins with multiple slashes

### ISSUE THREAD

**Issue by frankjkelly** [pact-foundation/pact-jvm#1701]
Gradle Plugin 4.6.1 (same results with prior version 4.2.7)
Upgrading Jars from 4.1.9 -> 4.6.1 

```
java.lang.IllegalArgumentException: URI path begins with multiple slashes
	at org.apache.hc.core5.util.Args.check(Args.java:41)
	at org.apache.hc.core5.http.message.BasicHttpRequest.setUri(BasicHttpRequest.java:281)
	at org.apache.hc.core5.http.message.BasicHttpRequest.<init>(BasicHttpRequest.java:123)
	at org.apache.hc.core5.http.message.BasicClassicHttpRequest.<init>(BasicClassicHttpRequest.java:91)
	at org.apache.hc.client5.http.classic.methods.HttpUriRequestBase.<init>(HttpUriRequestBase.java:45)
	at org.apache.hc.client5.http.classic.methods.HttpGet.<init>(HttpGet.java:50)
	at au.com.dius.pact.core.pactbroker.HalClient$getJson$1.invoke(HalClient.kt:311)
	at au.com.dius.pact.core.support.KotlinLanguageSupportKt.handleWith(KotlinLanguageSupport.kt:35)
	at au.com.dius.pact.core.pactbroker.HalClient.getJson(HalClient.kt:310)
	at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:274)
	at au.com.dius.pact.core.pactbroker.HalClient.fetchLink(HalClient.kt:354)
	at au.com.dius.pact.core.pactbroker.HalClient.navigate(HalClient.kt:261)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.fetchConsumers(PactBrokerClient.kt:443)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient$fetchConsumersWithSelectorsV2$1.invoke(PactBrokerClient.kt:520)
	at au.com.dius.pact.core.support.KotlinLanguageSupportKt.handleWith(KotlinLanguageSupport.kt:35)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.fetchConsumersWithSelectorsV2(PactBrokerClient.kt:514)
	at au.com.dius.pact.provider.junitsupport.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.kt:248)
	at au.com.dius.pact.provider.junitsupport.loader.PactBrokerLoader.load(PactBrokerLoader.kt:128)
	at au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider$resolvePactSources$pactSources$1$pacts$1.invoke(PactJUnit5VerificationProvider.kt:78)
	at au.com.dius.pact.core.support.KotlinLanguageSupportKt.handleWith(KotlinLanguageSupport.kt:35)
	at au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider.resolvePactSources(PactJUnit5VerificationProvider.kt:78)
	at au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider.provideTestTemplateInvocationContexts(PactJUnit5VerificationProvider.kt:45)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$0(TestTemplateTestDescriptor.java:106)
```

Our gradle code
```
task contract(type: Test) {
  description('Run provider verification')

  // Publish needed environment variables/system properties for Pact Broker
  def pactHost = System.getenv('PACT_URL') != null ? System.getenv('PACT_URL').split('//')[1] : "pact.ctrl.cogitocorp.us"
  systemProperty("pactbroker.host", pactHost)
  systemProperty('pactbroker.auth.username', System.getenv('PACT_CREDENTIALS_USR'))
  systemProperty('pactbroker.auth.password', System.getenv('PACT_CREDENTIALS_PSW'))
  systemProperty('pact.provider.tag', System.getProperty('pact.provider.tag', 'dev'))

  // Publish test result to Pact Broker
  // Only publish when running with CI process
  environment('pact.verifier.publishResults', System.getProperty('pact.verifier.publishResults', 'false') == 'true')
  useJUnitPlatform()
  group = 'verification'
  testClassesDirs = sourceSets.contract.output.classesDirs
  classpath = sourceSets.contract.runtimeClasspath
}
```

**Comment by frankjkelly** [comment]
Interestingly when I look in the Pact browser I see the following URL

![image](https://github.com/pact-foundation/pact-jvm/assets/62910985/e77dbf65-c02f-4a41-a7f1-f7e7b4e2867e)

Note the double slashes at the start of the URI
https://pact.ctrl.cogitocorp.us//pacts/provider/SignalContainerTypeAPI/consumer/OSS%20-%20Create%20Container%20Type/version/1.203.0

**Comment by rholshausen** [comment]
Could it be this bit? `System.getenv('PACT_URL').split('//')[1]`

**Comment by frankjkelly** [comment]
> Could it be this bit? `System.getenv('PACT_URL').split('//')[1]`

No `PACT_URL` is not set - in any event even if it was set, this worked previously with older versions.

**Comment by rholshausen** [comment]
It's just curios you have a double slash in your split. That tells me that PACT_URL would have a double slash in it. Also, you have an image from your pact broker with a double slash in the URL. So your broker is also configured in this manner.

The previous versions just may have not validated the URLs correctly.

**Comment by frankjkelly** [comment]
> It's just curios you have a double slash in your split. That tells me that PACT_URL would have a double slash in it. Also, you have an image from your pact broker with a double slash in the URL. So your broker is also configured in this manner.
> 
> The previous versions just may have not validated the URLs correctly.

Thanks - I am no groovy expert but I believe the code 
```
System.getenv('PACT_URL').split('//')[1]
```
Is splitting up a URL e.g. `http://helloworld` and extracting `helloworld` to populate for the `pactbroker.host`.  

I am not sure how the broker was configured - is there any documentation on how to setup a broker (the person who did it for us left the company). Thanks again

**Comment by rholshausen** [comment]
There are lots. See https://docs.pact.io/pact_broker/docker_images/pactfoundation. It is normally configured via environment variables.

**Comment by frankjkelly** [comment]
Thanks so much @rholshausen - when I finally tracked down the configuration it indeed had a trailing slash
```
          PACT_BROKER_BASE_URL: https://${hostname}/
```
