### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1 when query param with out value

### ISSUE THREAD

**Issue by WhiteBite** [pact-foundation/pact-jvm#1788]
I have some strange conroller

```java
    @GetMapping(params = "example-param")
    public LocalDate findActiveQualificationStartDate(ExampleDataDTO searchData) {
        return exampleService.findExampleData(searchData);
    }
    
```

And my query is
http://localhost:8080/?example-param&innerParam=Test1&innerParam2=Test2

And then when i can build pact
i make uri
    
```
    URIBuilder uriBuilder = new URIBuilder()
                .addParameter("qualification-start-date", null)
                ....
```
                
                
```
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

	at java.base/java.util.Collections$SingletonList.get(Collections.java:4959)
	at au.com.dius.pact.core.model.PactReaderKt.queryStringToMap(PactReader.kt:160)
	at au.com.dius.pact.consumer.dsl.PactDslRequestWithPath.query(PactDslRequestWithPath.kt:163)
	at pact.ExampleDataClientPactTest.createPact(ExampleDataClientPactTest.java:52)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by rholshausen** [comment]
4.6.9 has been released with a fix

**Comment by WhiteBite** [comment]
> 4.6.9 has been released with a fix

Can you compiler 4.5.9 for java 11 and depoy to maven?

**Comment by rholshausen** [comment]
4.5.9 released
