### ISSUE TITLE
"eachKeyLike" verification changing behaviour between PACT Provider versions

### ISSUE THREAD

**Issue by DanJKing** [pact-foundation/pact-jvm#1789]
We seem to have had a scenario where updating our provider side library is causing a failing in verification on an eachKeyLike matcher.

**The endpoint**

Example response JSON:
```
{
"abcde": {
      "name": "productSet",
      "value": "my-set-id"
    }
}
```

...where there will be any number of keys like  `abcde` , but with different values based on the body sent to the endpoint. The structure of the object hanging off the key will always be consistent, with a name and a value.

i.e.  this would also be a valid response
```
{
"abcde": {
      "name": "somename",
      "value": "somevalue"
    },
"rfgd": {
      "name": "somename2",
      "value": "somevalue2"
    }
}
```

**Consumer Matching Code:**

On the **consumer** side, the team have been using the `eachKeyLike` matcher to account for these behaviours:

```
val providerResponseBody = PactDslJsonBody()
            .eachKeyLike("abcde")
            .stringType("name", "productSet")
            .stringType("value", setId)
            .closeObject()
```

With version `"au.com.dius:pact-jvm-consumer-junit:4.0.10"`. 

On the **provider** side, when using `"au.com.dius.pact.provider:junit5:4.1.42"` we see the contract test passing.

However, when attempting to migrate the **provider** side to `"au.com.dius.pact.provider:junit5:4.6.0"` we see the following failure:

```
1) Verifying a pact between digital-merch.product-merch and search.locations - POST /api/locations/pairs with set ids has a matching body

    1.1) body: $ Actual map is missing the following keys: abcde

        {
        -  "abcde": {
        +  "pj41": {
            "name": "productSet",
            "value": "my-set-id"
          }
        }
```

So, from my reading, it's now complaining that in the response it got back from the endpoint during the verification, it received the `pj41` key, not the `abcde` key.

Are you able to explain why this is happening? It looks as though the later provider side version is doing some kind of value matching in the verification now, whereas clearly in the previous version we used it did not. 

The PACT is generated from the consumer side to the designated Spec, and that code has not changed, so our assumption was updating the Provider side library should not cause this kind of issue?

Thanks

**Comment by rholshausen** [comment]
Can you provide your Pact file and debug logs?

**Comment by DanJKing** [comment]
Hi - see below:

Debug logs from the verification step in our pipeline:

```
POST /api/locations/pairs with set ids
        returns a response which
          has status code 200 (OK)
          has a matching body (FAILED)
    Failures:
    1) Verifying a pact between digital-merch.product-merch and search.locations - POST /api/locations/pairs with set ids has a matching body
        1.1) body: $ Actual map is missing the following keys: abcde
            {
            -  "abcde": {
            +  "pj41": {
                "name": "productSet",
                "value": "my-set-id"
              }
            }
Gradle Test Executor 1 finished executing tests.
> Task :test FAILED
LocationsContractTest > pactVerificationTestTemplate$contract_tests_test(PactVerificationContext) > Pact between digital-merch.product-merch (7ed80124) and search.locations - POST /api/locations/pairs with set ids FAILED
    java.lang.AssertionError: Pact between digital-merch.product-merch (7ed80124) and search.locations - Upon POST /api/locations/pairs with set ids 
    Failures:
    1) Verifying a pact between digital-merch.product-merch and search.locations - POST /api/locations/pairs with set ids has a matching body
        1.1) body: $ Actual map is missing the following keys: abcde
            {
            -  "abcde": {
            +  "pj41": {
                "name": "productSet",
                "value": "my-set-id"
              }
            }
        at au.com.dius.pact.provider.junit5.PactVerificationContext.verifyInteraction(PactVerificationContext.kt:75)
        at LocationsContractTest.pactVerificationTestTemplate$contract_tests_test(LocationsProviderContractTest.kt:24)
1 test completed, 1 failed
```

And the PACT uploaded to the broker:
```
{
  "provider": {
    "name": "search.locations"
  },
  "consumer": {
    "name": "digital-merch.product-merch"
  },
  "interactions": [{
    "_id": "c343ef7729664e473a8b425954fe94cf4e55afc8",
    "description": "POST /api/locations/pairs with set ids",
    "request": {
      "method": "POST",
      "path": "/api/locations/pairs",
      "headers": {
        "Content-Type": "application/json"
      },
      "body": [{
        "name": "productSet",
        "value": "my-set-id"
      }],
      "matchingRules": {
        "body": {
          "$[0].name": {
            "matchers": [{
              "match": "type"
            }],
            "combine": "AND"
          },
          "$[0].value": {
            "matchers": [{
              "match": "type"
            }],
            "combine": "AND"
          }
        }
      }
    },
    "response": {
      "status": 200,
      "headers": {
        "Content-Type": "application/json"
      },
      "body": {
        "abcde": {
          "name": "productSet",
          "value": "my-set-id"
        }
      },
      "matchingRules": {
        "body": {
          "$.*": {
            "matchers": [{
              "match": "type"
            }],
            "combine": "AND"
          },
          "$.*.name": {
            "matchers": [{
              "match": "type"
            }],
            "combine": "AND"
          },
          "$.*.value": {
            "matchers": [{
              "match": "type"
            }],
            "combine": "AND"
          }
        }
      }
    }
  }],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    },
    "pact-jvm": {
      "version": "4.0.8"
    }
  },
  "createdAt": "2024-04-21T13:47:08+00:00"
}
```

Cheers

**Comment by rholshausen** [comment]
4.1.x doesn't properly support the each-key matcher. Either upgrade your consumer to use 4.6.x and re-run the test.

If you can't upgrade to a 4.6 version, you can upgrade the consumer side to 4.1.42 and then set
```java
FeatureToggles.toggleFeature(Feature.UseMatchValuesMatcher, true);
val providerResponseBody = PactDslJsonBody()
            .eachKeyLike("abcde")
            .stringType("name", "productSet")
            .stringType("value", setId)
            .closeObject()
```
in the consumer test. Note that this will generate a Pact file that can't be verified with a 4.1 version, but will pass ok with 4.6.

You should use the latest 4.6 version which is currently 4.6.9.

**Comment by jemmawells-jlp** [comment]
Hi, apologies for jumping on this old thread. I'm looking back into the above to unblock some upgrades. This time we're looking at it from the consumer side while attempting to upgrade to 4.6. NB the provider has remained on version 4.1 since this issue was originally raised. 

In our consumer test, we have this: 

```
val providerResponseBody = newJsonBody { jsonBody ->
            jsonBody.eachValueLike("abcde") { jsonObject ->
                jsonObject.stringType("name", "productSet")
                jsonObject.stringType("value", setId)
            }
        }.build()
```

I can see that when using consumer version 4.6, eachKeyLike wants to match on values, whereas previously we were relying on it matching on type. We don't want to match on the value. Comparing the pact files from 4.1.x and 4.6...

4.0.10:

```
        "matchingRules": {
          "body": {
            "$.*": {
              "matchers": [
                {
                  "match": "type"
                }
              ],
              "combine": "AND"
            },
            "$.*.name": {
              "matchers": [
                {
                  "match": "type"
                }
              ],
              "combine": "AND"
            },
            "$.*.value": {
              "matchers": [
                {
                  "match": "type"
                }
              ],
              "combine": "AND"
            }
          }
        }
```

```
       "matchingRules": {
          "body": {
            "$": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "values"
                }
              ]
            },
            "$.*.name": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "type"
                }
              ]
            },
            "$.*.value": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "type"
                }
              ]
            }
          }
        }
```

Is it correct that the newer implementation of eachKeyLike is a values matcher now? If so, is there a suitable alternative we might be able to use to continue matching on type?  

Thanks.

**Comment by rholshausen** [comment]
`eachValueLike` adds the `"match": "values"` matcher in 4.6. This is a matcher that is only applied to the values in a Map (or Object in JSON). I.e., it ignores the keys. The other two entries are more specific, and apply a type matcher to those fields. This is equivalent to the previous implementation, just making it more explicit.

`eachKeyLike` can then be used add rules for the keys, i.e. if they need to match a specific regex.
