### ISSUE TITLE
`FileNotFoundException` error during Pact verification due to @VerificationReports' no longer setting a default `reportDir`

### ISSUE THREAD

**Issue by diogo-hs** [pact-foundation/pact-jvm#1836]
After upgrading to a more recent version of Pact provider (`4.0.10` -> `4.6.15`), we started to get the following error:

```
/XXX.md (Read-only file system)java.io.FileNotFoundException: /XXX.md (Read-only file system)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:113)
	at au.com.dius.pact.provider.reporters.MarkdownReporter.generateReportFile(MarkdownReporter.kt:90)
	at au.com.dius.pact.provider.reporters.MarkdownReporter.finaliseReport(MarkdownReporter.kt:85)
	at au.com.dius.pact.provider.ProviderVerifier.finaliseReports(ProviderVerifier.kt:911)
	at au.com.dius.pact.provider.junit5.PactVerificationContext.verifyInteraction(PactVerificationContext.kt:80)
	...
```

Debugging a bit, we realized that `@VerificationReports("console", "markdown")` was no longer working because its `reportDir` no longer sets the default value it previously used to (and which's stated [in the docs](https://docs.pact.io/implementation_guides/jvm/provider/junit#enabling-additional-reports-via-java-system-properties-or-environment-variables)).

I'm not sure about the motivation for removing the default value on the following commit, but if that's required, it'd be good to have the docs updated (since they're misleading as of now):

https://github.com/pact-foundation/pact-jvm/commit/616d8808a6a9f72418ebc6085d5a7fc1818dcf0d#diff-85bd7c5d2cbc991a6a28288452241974a39a8d3f2c6a1b1bf94c1a2ac424325f

**Comment by rholshausen** [comment]
That's a regression

**Comment by rholshausen** [comment]
Ok, that's not quite true. The reason for the change, is that the default value should be different depending if the project is using Gradle or Maven (previous default value is for a Maven project). So the docs are out of date in that sense.

However, that change only meant that the default should now change between `build/pacts/reports` and `target/pacts/reports`. Something must be setting it to `/` for you.

**Comment by rholshausen** [comment]
With my test, the default value is set correctly.

**Comment by diogo-hs** [comment]
Yeah, I figured it out on our side, it was my fault. Thank you for the help! 🙏
