### ISSUE TITLE
File handler leak causing java.io.IOException: Too many open files exception

### ISSUE THREAD

**Issue by BenSayers** [pact-foundation/pact-jvm#406]
There appears to be a file handler leak in the pact-ivm implementation causing IOExceptions.

**Steps to reproduce:**

**Create some example Pact tests**
```java

public class ExampleTest {
    private static final String CONSUMER_NAME = "example-consumer";
    private static final String PROVIDER_NAME = "example-provider";

    private UserProxy userProxy;

    private static void outputOpenFileCount(String prefix) {
        OperatingSystemMXBean os = ManagementFactory.getOperatingSystemMXBean();
        if(os instanceof UnixOperatingSystemMXBean){
            System.out.println(prefix + ": Number of open fd: " + ((UnixOperatingSystemMXBean) os).getOpenFileDescriptorCount());
        }
    }

    @Rule
    public PactProviderRule provider = new PactProviderRule(PROVIDER_NAME, "localhost", 8081, this);

    @BeforeClass
    public static void beforeAll() {
        outputOpenFileCount("beforeAll");
    }

    @Before
    public void beforeEach() {
        userProxy = new UserProxy();
        outputOpenFileCount("beforeEach");
    }

    @After
    public void afterEach() {
        outputOpenFileCount("afterEach");
    }

    @Pact(consumer = CONSUMER_NAME)
    public PactFragment getUserFragment(PactDslWithProvider builder) {
        Map<String, String> responseHeaders = new HashMap<>();
        responseHeaders.put("Content-Type", "application/json;charset=UTF-8");

        String responseBody = new JSONObject()
                .put("userId", 2)
                .put("firstName", "Bob")
                .put("lastName", "Smith")
                .put("email", "bsmith@domain.com")
                .toString();

        return builder
                .given("there is one user in the database")
                .uponReceiving("a request for user 2 on account 1")
                .path("/1/users/2")
                .method("GET")
                .willRespondWith()
                .status(200)
                .headers(responseHeaders)
                .body(responseBody)
                .toFragment();
    }

    @Test
    @PactVerification(fragment = "getUserFragment")
    public void shouldGetAUser() {
        Either<ApplicationException, User> result = userProxy.get(1, 2);

        assertThat("result is success", result.isRight(), is(true));
        User expectedUser = new User()
                .setUserId(2)
                .setFirstName("Bob")
                .setLastName("Smith")
                .setEmail("bsmith@domain.com");
        assertThat(result.right().get(), is(expectedUser));
    }

    @Pact(consumer = CONSUMER_NAME)
    public PactFragment getMissingUserFragment(PactDslWithProvider builder) {
        return builder
                .given("there is one user in the database")
                .uponReceiving("a request for user 3 on account 1")
                .path("/1/users/3")
                .method("GET")
                .willRespondWith()
                .status(404)
                .toFragment();
    }

    @Test
    @PactVerification(fragment = "getMissingUserFragment")
    public void shouldReturnANotFoundApplicationExceptionWhenTheUserIsNotFound() {
        Either<ApplicationException, User> result = userProxy.get(1, 3);
        assertThat("result is failure", result.isLeft(), is(true));
        assertThat(result.left().get().getReason(), Is.is(ApplicationExceptionReason.NOT_FOUND));
    }

    @Pact(consumer = CONSUMER_NAME)
    public PactFragment getMissingAccountFragment(PactDslWithProvider builder) {
        return builder
                .given("there is one user in the database")
                .uponReceiving("a request for user 1 on account 2")
                .path("/2/users/1")
                .method("GET")
                .willRespondWith()
                .status(404)
                .toFragment();
    }

    @Test
    @PactVerification(fragment = "getMissingAccountFragment")
    public void shouldReturnANotFoundApplicationExceptionWhenTheAccountIsNotFound() {
        Either<ApplicationException, User> result = userProxy.get(2, 1);
        assertThat("result is failure", result.isLeft(), is(true));
        assertThat(result.left().get().getReason(), Is.is(ApplicationExceptionReason.NOT_FOUND));
    }

    @Pact(consumer = CONSUMER_NAME)
    public PactFragment getServerErrorFragment(PactDslWithProvider builder) {
        return builder
                .given("the user service is down")
                .uponReceiving("a request for a user that results in a server error")
                .path("/1/users/4")
                .method("GET")
                .willRespondWith()
                .status(500)
                .toFragment();
    }

    @Test
    @PactVerification(fragment = "getServerErrorFragment")
    public void shouldReturnAnUnknownApplicationExceptionWhenAServerErrorOccurs() {
        Either<ApplicationException, User> result = userProxy.get(1, 4);
        assertThat("result is failure", result.isLeft(), is(true));
        assertThat(result.left().get().getReason(), is(ApplicationExceptionReason.UNKNOWN));
    }
}
```

**Change the ulimit to a reasonable value**
```
ulimit -n 300
```

**Run the Pact tests**
```
mvn test
```

**Result**
```
beforeAll: Number of open fd: 102
beforeEach: Number of open fd: 205
afterEach: Number of open fd: 211

au.com.dius.pact.consumer.PactMismatchException: Pact verification failed for the following reasons:

The following requests were not received:
Interaction: a request for a user that results in a server error
	in state the user service is down
request:
	method: GET
	path: /1/users/4
	query: [:]
	headers: [:]
	matchers: [:]
	body: au.com.dius.pact.model.OptionalBody(MISSING, null)

response:
	status: 500
	headers: [:]
	matchers: [:]
	body: au.com.dius.pact.model.OptionalBody(MISSING, null)
	at au.com.dius.pact.consumer.PactProviderRule.validateResult(PactProviderRule.java:225)
	at au.com.dius.pact.consumer.PactProviderRule.access$200(PactProviderRule.java:27)
	at au.com.dius.pact.consumer.PactProviderRule$1.evaluate(PactProviderRule.java:136)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:48)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:40)
	at unfiltered.netty.Engine$Default$.workers(Engine.scala:22)
	at unfiltered.netty.Engine$Default$.workers(Engine.scala:20)
	at unfiltered.netty.Server.unfiltered$netty$Server$$workerGrp$lzycompute(Server.scala:43)
	at unfiltered.netty.Server.unfiltered$netty$Server$$workerGrp(Server.scala:43)
	at unfiltered.netty.Server$$anonfun$2.apply(Server.scala:68)
	at unfiltered.netty.Server$$anonfun$2.apply(Server.scala:65)
	at scala.collection.immutable.List.map(List.scala:273)
	at unfiltered.netty.Server.start(Server.scala:65)
	at unfiltered.netty.Server.start(Server.scala:60)
	at au.com.dius.pact.consumer.UnfilteredMockProvider.start(UnfilteredMockProvider.scala:33)
	at au.com.dius.pact.consumer.StatefulMockProvider.start(MockProvider.scala:45)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:59)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:58)
	at scala.util.Try$.apply(Try.scala:192)
	at au.com.dius.pact.consumer.StatefulMockProvider.runAndClose(MockProvider.scala:57)
	at au.com.dius.pact.consumer.ConsumerPactRunner.runAndWritePact(ConsumerPactRunner.scala:31)
	at au.com.dius.pact.model.PactFragment.duringConsumerSpec(PactFragment.scala:13)
	at au.com.dius.pact.model.PactFragment.runConsumer(PactFragment.scala:21)
	at au.com.dius.pact.consumer.PactProviderRule.runPactTest(PactProviderRule.java:207)
	at au.com.dius.pact.consumer.PactProviderRule.access$100(PactProviderRule.java:27)
	at au.com.dius.pact.consumer.PactProviderRule$1.evaluate(PactProviderRule.java:135)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:152)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:143)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:48)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:40)
	at unfiltered.netty.Engine$Default$.workers(Engine.scala:22)
	at unfiltered.netty.Engine$Default$.workers(Engine.scala:20)
	at unfiltered.netty.Server.unfiltered$netty$Server$$workerGrp$lzycompute(Server.scala:43)
	at unfiltered.netty.Server.unfiltered$netty$Server$$workerGrp(Server.scala:43)
	at unfiltered.netty.Server$$anonfun$2.apply(Server.scala:68)
	at unfiltered.netty.Server$$anonfun$2.apply(Server.scala:65)
	at scala.collection.immutable.List.map(List.scala:273)
	at unfiltered.netty.Server.start(Server.scala:65)
	at unfiltered.netty.Server.start(Server.scala:60)
	at au.com.dius.pact.consumer.UnfilteredMockProvider.start(UnfilteredMockProvider.scala:33)
	at au.com.dius.pact.consumer.StatefulMockProvider.start(MockProvider.scala:45)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:59)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:58)
	at scala.util.Try$.apply(Try.scala:192)
	at au.com.dius.pact.consumer.StatefulMockProvider.runAndClose(MockProvider.scala:57)
	at au.com.dius.pact.consumer.ConsumerPactRunner.runAndWritePact(ConsumerPactRunner.scala:31)
	at au.com.dius.pact.model.PactFragment.duringConsumerSpec(PactFragment.scala:13)
	at au.com.dius.pact.model.PactFragment.runConsumer(PactFragment.scala:21)
	at au.com.dius.pact.consumer.PactProviderRule.runPactTest(PactProviderRule.java:207)
	at au.com.dius.pact.consumer.PactProviderRule.access$100(PactProviderRule.java:27)
	at au.com.dius.pact.consumer.PactProviderRule$1.evaluate(PactProviderRule.java:135)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.IOException: Too many open files
	at sun.nio.ch.IOUtil.makePipe(Native Method)
	at sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:84)
	at sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:42)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:150)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:143)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:48)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:40)
	at unfiltered.netty.Engine$Default$.workers(Engine.scala:22)
	at unfiltered.netty.Engine$Default$.workers(Engine.scala:20)
	at unfiltered.netty.Server.unfiltered$netty$Server$$workerGrp$lzycompute(Server.scala:43)
	at unfiltered.netty.Server.unfiltered$netty$Server$$workerGrp(Server.scala:43)
	at unfiltered.netty.Server$$anonfun$2.apply(Server.scala:68)
	at unfiltered.netty.Server$$anonfun$2.apply(Server.scala:65)
	at scala.collection.immutable.List.map(List.scala:273)
	at unfiltered.netty.Server.start(Server.scala:65)
	at unfiltered.netty.Server.start(Server.scala:60)
	at au.com.dius.pact.consumer.UnfilteredMockProvider.start(UnfilteredMockProvider.scala:33)
	at au.com.dius.pact.consumer.StatefulMockProvider.start(MockProvider.scala:45)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:59)
	at au.com.dius.pact.consumer.StatefulMockProvider$$anonfun$runAndClose$1.apply(MockProvider.scala:58)
	at scala.util.Try$.apply(Try.scala:192)
	at au.com.dius.pact.consumer.StatefulMockProvider.runAndClose(MockProvider.scala:57)
	at au.com.dius.pact.consumer.ConsumerPactRunner.runAndWritePact(ConsumerPactRunner.scala:31)
	at au.com.dius.pact.model.PactFragment.duringConsumerSpec(PactFragment.scala:13)
	at au.com.dius.pact.model.PactFragment.runConsumer(PactFragment.scala:21)
	at au.com.dius.pact.consumer.PactProviderRule.runPactTest(PactProviderRule.java:207)
	at au.com.dius.pact.consumer.PactProviderRule.access$100(PactProviderRule.java:27)
	at au.com.dius.pact.consumer.PactProviderRule$1.evaluate(PactProviderRule.java:135)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by rholshausen** [comment]
Closing this is it looks like it is no longer a problem. Running a modified version of the test above, I can see:
```
beforeAll: Number of open fd: 190
beforeEach: Number of open fd: 192
afterEach: Number of open fd: 194
beforeEach: Number of open fd: 193
afterEach: Number of open fd: 194
beforeEach: Number of open fd: 193
afterEach: Number of open fd: 194
beforeEach: Number of open fd: 193
afterEach: Number of open fd: 194
```

and  there are no unexpected IO exceptions.
