### ISSUE TITLE
pact-jvm-provider-maven plugin cannot process broker error responses

### ISSUE THREAD

**Issue by marcevers** [pact-foundation/pact-jvm#421]
When publishing a pact that is rejected by the pact broker (e.g. because of an invalid version), the pact-jvm-provider maven plugin is unable to process the error response from the broker. It fails with:

Caused by: groovy.lang.MissingMethodException: No signature of method: groovy.json.internal.LazyMap.join() is applicable for argument types: (java.lang.String) values: [, ]
Possible solutions: min(groovy.lang.Closure), wait(), sort(), find(), wait(long), print(java.lang.Object)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:177)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at au.com.dius.pact.provider.broker.PactBrokerClient$_uploadPactFile_closure3$_closure5.doCall(PactBrokerClient.groovy:83)
	...

This issue occurs with pact-jvm 3.3.7 and 3.3.8 and publishing to the hosted pact broker.

**Comment by LoraVolkert** [comment]
I'm also seeing this issue with version 3.5.4-jre7.0.
