### ISSUE TITLE
Add relocate feature to shadowing in fat jar

### ISSUE THREAD

**Issue by LoraV** [pact-foundation/pact-jvm#888]
I've run into issues with past and current versions of the fat jar. Today, I was adding some consumer pacts to a project that was transitively packaging version 1.2.71 of kotlin-stdlib and kotlin-stdlib-jdk8. That version of kotlin collided with the version being used in pact jvm 3.6.7. I got invocation target exceptions.

> java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at au.com.dius.pact.model.PactWriter.writePact(PactWriter.kt:51)
	at au.com.dius.pact.consumer.BaseMockServer.runAndWritePact(MockHttpServer.kt:195)
	at au.com.dius.pact.consumer.ConsumerPactRunnerKt.runConsumerTest(ConsumerPactRunner.kt:13)
	at au.com.dius.pact.consumer.BaseProviderRule.runPactTest(BaseProviderRule.java:158)
	at au.com.dius.pact.consumer.BaseProviderRule.access$100(BaseProviderRule.java:22)
	at au.com.dius.pact.consumer.BaseProviderRule$1.evaluate(BaseProviderRule.java:78)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.IllegalAccessError: class kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance tried to access private method kotlin.collections.ArraysKt___ArraysJvmKt.copyOfRange([Ljava/lang/Object;II)[Ljava/lang/Object; (kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance and kotlin.collections.ArraysKt___ArraysJvmKt are in unnamed module of loader 'app')
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:251)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at au.com.dius.pact.model.generators.GeneratorKt.lookupGenerator(Generator.kt:47)
	at au.com.dius.pact.model.generators.Generators$Companion.fromMap(Generators.kt:126)
	at au.com.dius.pact.model.generators.Generators.fromMap(Generators.kt)
	at au.com.dius.pact.model.Response$_fromMap_closure1.doCall(Response.groovy:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:369)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:316)
	at org.codehaus.groovy.runtime.dgm$827.doMethodInvoke(Unknown Source)
	at au.com.dius.pact.model.Response.fromMap(Response.groovy:26)
	at au.com.dius.pact.model.PactReader.extractResponse(PactReader.groovy:96)
	at au.com.dius.pact.model.PactReader$_loadV3Pact_closure1.doCall(PactReader.groovy:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
	at groovy.lang.Closure.call(Closure.java:421)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3540)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3525)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3625)
	at org.codehaus.groovy.runtime.dgm$87.doMethodInvoke(Unknown Source)
	at au.com.dius.pact.model.PactReader.loadV3Pact(PactReader.groovy:58)
	at au.com.dius.pact.model.PactReader.loadPact(PactReader.groovy:41)
	at au.com.dius.pact.model.PactReader.loadPact(PactReader.groovy)
	... 28 more

I had to move to explicit dependencies of the pact-jvm consumer sublibraries and kotlin (version 1.3.30) in order to fix it.

I notice that line 17 of the current version of the build.gradle file has "apply false" on the 'com.github.johnrengelman.shadow' plugin. I also noticed that early versions of build files for the fat jar had a shadowJar section, but it no longer exists: https://github.com/DiUS/pact-jvm/commit/6989edf5d3378e735ced7c3190097a9792d7e563

The little bit I've read about applying shadowing does make it sound like it would fix this problem for us.

**Comment by uglyog** [comment]
The `apply: false` on line 17 is to have the plugin loaded but not applied to all projects. Line 285 then applies it when the fat jar is built.

**Comment by uglyog** [comment]
The Kotlin libraries have been excluded from the fat jar, and will now be applied transiently.

**Comment by LoraV** [comment]
I've had issues with the Junit libraries in the past, as well. Can we do the same with those?

**Comment by LoraV** [comment]
This does seem like it defeats the whole point of the fat jar, though. There should be some way of including kotlin and junit but also renaming or changing the paths on everything so we don't get weird conflicts.

**Comment by LoraV** [comment]
This seems like a pervasive issue. One of our projects is on an older version of pact, 3.5.24. I'm trying to upgrade it, and failing. They were using the _2.11 artifacts, so of course I had to change that. When I use the standalone junit and java8 artifacts, I get missing scala method errors:

> java.lang.RuntimeException: Failed to invoke pact method

	at au.com.dius.pact.consumer.BaseProviderRule.getPacts(BaseProviderRule.java:195)
	at au.com.dius.pact.consumer.BaseProviderRule$1.evaluate(BaseProviderRule.java:64)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at au.com.dius.pact.consumer.BaseProviderRule.getPacts(BaseProviderRule.java:192)
	... 16 more
Caused by: java.lang.NoSuchMethodError: scala.util.parsing.combinator.Parsers.$init$(Lscala/util/parsing/combinator/Parsers;)V
	at io.gatling.jsonpath.Parser$.<init>(Parser.scala:62)
	at io.gatling.jsonpath.Parser$.<clinit>(Parser.scala)
	at au.com.dius.pact.consumer.dsl.PactDslJsonBody.matcherKey(PactDslJsonBody.java:192)
	at au.com.dius.pact.consumer.dsl.PactDslJsonBody.stringType(PactDslJsonBody.java:186)
	at io.pactfoundation.consumer.dsl.LambdaDslObject.stringType(LambdaDslObject.java:30)

When I switch to the fat jar, the Pact tests pass, but other (non-Pact) tests that are relying on more up-to-date versions of guava and jackson than pact-jvm start failing:

> java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;

	at com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:50)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:565)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
	at com.ca.json2.utils.JsonUtils2.<clinit>(JsonUtils2.java:50)

> Error:(315, 17) java: cannot find symbol
  symbol:   method forEach((row,data)[...]y); })
  location: interface com.google.common.collect.ListMultimap<com.ca.phoebe.ws.rule.PhoebeDataSetRow,com.ca.phoebe.ws.util.PhoebeDataMap>

> java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap.toImmutableMap(Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;

**Comment by LoraV** [comment]
I'm pretty sure this is all you need: 

`// Relocating a Package
shadowJar {
   relocate 'junit.framework', 'shadow.junit'
}`

See https://imperceptiblethoughts.com/shadow/configuration/relocation/#filtering-relocation

**Comment by TravelinMax** [comment]
@uglyog what makes you think the Kotlin dependency cannot be shaded?

And I'm with @LoraV I think all the dependencies should be shaded. If I have to pull in different dependencies for my tests then I'm not really testing my application. Maybe less important for contract tests but the dependency hell is still a massive headache.

**Comment by uglyog** [comment]
I just have a feeling that that is something that can cause issues. We can try it, but I think mixing Kotlin versions is always going to be a problem.

**Comment by TravelinMax** [comment]
I did a little bit of research last night and only came up with a few random forum posts but 2 of them said "it works" and 1 said "it probably won't work" so there's probably a 2/3rds chance it might work 😆.

Either way it's not even Kotlin that I'm having trouble with (yet...), it's Groovy. I've just been messing around with Pact in an app that uses Groovy 2.5.8 but I couldn't get Pact working until I brought the pact-jvm-* dependencies down to 3.5.14 and Groovy down to 2.4.something, which of course meant I also had to downgrade my Spock dependencies from 1.2-groovy-2.5 to 1.2-groovy-2.4.

Now that I think of it, if you're using Kotlin you must not be using Groovy so why is it dependent on it? A transitive dependency then? Maybe we could try to get that out of the project? I'm better at rambling than I am at implementation but maybe I could help with something like this if you want.

**Comment by TravelinMax** [comment]
I _did_ figure out the specific issue I am having with groovy, the [3.5.x and 3.6.x branches rely on the groovy-all:${version}-indy.jar](https://github.com/DiUS/pact-jvm/blob/v3.5.x/build.gradle#L93) but the indy jar was removed in groovy 3.5.0. I don't know what the issue I was having with the 4.0.0 branch was because I gave up on that one as soon as it wasn't working because it was so new. If my issues with 4.0.0 turn out to be relevant I'll report back on them.

**Comment by uglyog** [comment]
Something else must be causing the problem, because Pact-JVM uses Spock for most of the tests (spock-core:1.3-groovy-2.5). I know I have to exclude Groovy from some dependencies to get the correct version.

**Comment by YOU54F** [comment]
fix was implemented here https://github.com/pact-foundation/pact-jvm/commit/2832d4dfad5a23213e2af3d784b1b3561dbe1024

as per

https://github.com/pact-foundation/pact-jvm/issues/888#issuecomment-503618199

if this is still an issue, please raise a new one, and reference this, thanks!
